// Code generated by "generate_embed"; DO NOT EDIT.
package main

var queries = map[string]string{
	"insert.sql":                     "insert into jobs(url)\n    values($1)\n    returning id;",
	"insert_retries.sql":             "insert into jobs(url, retries)\n    values($1, $2)\n    returning id;",
	"select_detail.sql":              "select\n    url, started_at, error, output, torlog\n    from jobs\n    where id = $1;",
	"select_done.sql":                "select\n    id, url, started_at, downloaded_at, uploaded_at, output, error, retries, geoip->>'ip' as ip, geoip->>'country_name' as country\n    from jobs\n    where status = 'done'\n    order by started_at desc\n    limit 100;",
	"select_error.sql":               "select\n    id, url, started_at, error, retries, geoip->>'ip' as ip, geoip->>'country_name' as country\n    from jobs\n    where status = 'error'\n    order by started_at desc\n    limit 100;",
	"select_running.sql":             "select\n    url, started_at, retries, geoip->>'ip' as ip, geoip->>'country_name' as country\n    from jobs\n    where status = 'running'\n    order by started_at desc;",
	"update_error.sql":               "update jobs\n    set status = 'error', error = $1\n    where id = $2;",
	"update_geoip.sql":               "update jobs\n    set geoip = $1\n    where id = $2;",
	"update_output.sql":              "update jobs\n    set output = $1, downloaded_at = $2\n    where id = $3;",
	"update_output_error.sql":        "update jobs\n    set status = 'error', output = $1, error = $2\n    where id = $3;",
	"update_output_error_torlog.sql": "update jobs\n    set status = 'error', output = $1, error = $2, torlog = $3\n    where id = $4;",
	"update_uploaded_at.sql":         "update jobs\n    set status = 'done', uploaded_at = $1\n    where id = $2;",
}
var templates = map[string]string{
	"base.html":    "{{define \"head\"}}\n<html>\n    <head>\n        <title>youtube-ar</title>\n        <style>\n            table {border-collapse:collapse;}\n            table, th, td {border: 1px solid;}</style>\n    </head>\n    <body>\n        <form action=\"/\" method=\"post\">\n            <input name=\"url\">\n        </form>\n        <div>\n            <a href=\"/\">Running</a>\n            <a href=\"/done/\">Done</a>\n            <a href=\"/errors/\">Errors</a>\n        </div>\n        <hr>\n{{end}}\n\n{{define \"foot\"}}\n    </body>\n</html>\n{{end}}",
	"detail.html":  "{{template \"head\"}}\n<h2><a href=\"{{.URL}}\">{{.URL}}</a></h2> {{ago .StartedAt}}\n{{if .Output}}<h3>Output</h3><pre>{{.Output}}</pre>{{end}}\n{{if .Error}}<h3>Error</h3><pre>{{.Error}}</pre>{{end}}\n{{if .TorLog}}<h3>TorLog</h3><pre>{{.TorLog}}</pre>{{end}}\n{{template \"foot\"}}",
	"done.html":    "{{template \"head\"}}\n<table>\n    <th>URL</th><th>Started</th><th>Downloaded</th><th>Uploaded</th><th>Retries</th><th>IP</th>\n    {{range .}}\n    <tr>\n        <td><a href=\"/detail/{{.ID}}/\">{{.URL}}</a></td>\n        <td>{{ago .StartedAt}}</td>\n        <td>{{if .DownloadedAt}}{{ago .DownloadedAt}}{{end}}</td>\n        <td>{{if .UploadedAt}}{{ago .UploadedAt}}{{end}}</td>\n        <td>{{.Retries}}</td>\n        <td>{{if .IP}}{{.IP}}{{if .Country}} ({{.Country}}){{end}}{{end}}</td>\n    </tr>\n    {{end}}\n</table>\n{{template \"foot\"}}",
	"errors.html":  "{{template \"head\"}}\n<table>\n    <th>URL</th><th>Started</th><th>Retries</th><th>IP</th><th>Error</th>\n    {{range .}}\n    <tr>\n        <td><a href=\"/detail/{{.ID}}/\">{{.URL}}</a></td>\n        <td>{{ago .StartedAt}}</td>\n        <td>{{.Retries}}</td>\n        <td>{{if .IP}}{{.IP}}{{if .Country}} ({{.Country}}){{end}}{{end}}</td>\n        <td>{{.Error}}</td>\n    </tr>\n    {{end}}\n</table>\n{{template \"foot\"}}",
	"running.html": "{{template \"head\"}}\n<table>\n    <th>URL</th><th>Started</th><th>Retries</th><th>IP</th>\n    {{range .}}\n    <tr>\n        <td>{{.URL}}</td>\n        <td>{{ago .StartedAt}}</td>\n        <td>{{.Retries}}</td>\n        <td>{{if .IP}}{{.IP}}{{if .Country}} ({{.Country}}){{end}}{{end}}</td>\n    </tr>\n    {{end}}\n</table>\n{{template \"foot\"}}",
}
